baseURL = "https://zalas.pl/"
languageCode = "en-gb"
title = "Kuba's blog"
theme = "PaperMod"

author = "Jakub Zalas"
copyright = "Copyright Â© 2009â€“{{< year >}} Jakub Zalas; all rights reserved."

googleAnalytics = "G-CVLMK236R4"

[permalinks]
  posts = "/:slug/"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[params]
  ShowReadingTime = true
  ShowWordCount = true
  DefaultTheme = "light"
  ShowToc = true
  comments = true
  author = "Jakub Zalas"
  hideFooter = true
  DisableHLJS = true
  description = "Jakub Zalas is a software engineer, architect, and trainer who takes great pride in his craft and quality of work. Friends call him Kuba. Get in touch for consultancy, training or software development."
  keywords = ["Jakub Zalas", "Kuba Zalas", "Jakub Zalas blog", "software engineer", "software architect", "Jakub Zalas trainer", "consultant", "trainer", "tdd", "bdd", "ddd", "test-driven development", "behaviour-driven development", "domain-driven design", "event sourcing", "kotlin", "java", "php", "csharp"]
  images = ["jakub-zalas.jpeg", "death-valley.jpg"]

  [analytics]
    [google]
      SiteVerificationTag = "Yim4XSvn_4ENuO8C3sFnYJh0y31W8yVh7pFrlpS-RZY"

  [assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    appleTouchIcon = "favicon.png"
    safariPinnedTab = "favicon.png"

  [[params.socialIcons]]
    name = "github"
    title = "Jakub Zalas on Github"
    url = "https://github.com/jakzal"

  [[params.socialIcons]]
    name = "X"
    title = "Jakub Zalas on X/Twitter"
    url = "https://x.com/jakub_zalas"

  [[params.socialIcons]]
    name = "Bluesky"
    title = "Jakub Zalas on Bluesky"
    url = "https://bsky.app/profile/kuba.zalas.pl"

  [[params.socialIcons]]
    name = "Mastodon"
    title = "Jakub Zalas on Mastodon"
    url = "https://mastodon.social/@jakub_zalas"

  [[params.socialIcons]]
    name = "LinkedIn"
    title = "Jakub Zalas on LinkedIn"
    url = "https://www.linkedin.com/in/jakubzalas/"

  [params.profileMode]
    enabled = true
    title = "Jakub Zalas {{< sup >}}a.k.a. Kuba{{< /sup >}}"
    imageUrl = "jakub-zalas.jpeg"
    imageTitle = "Jakub Zalas"
    subtitle = "ğŸ‘¨ğŸ¼â€ğŸ’¼ Software Architect | ğŸ§‘ğŸ¼â€ğŸ’» Developer | ğŸ§‘ğŸ¼â€ğŸ« Trainer"

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts/"

    [[params.profileMode.buttons]]
      name = "Tags"
      url = "/tags/"

[services]
  [services.disqus]
    shortname = 'kubas-blog'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
